### ISSUE TITLE
Reliance image printing is malformed

### ISSUE THREAD

**Issue by yeuchi** [PyramidTechnologies/PTI.Reliance.Tools#5]
https://drive.google.com/file/d/1FDkblkK8d7qA6x0H6J-VcGt03vzD-sTb/view

Hi Cory, Here is a video clip of a 640x640 image jamming.

thanks for your consideration,

Chi - Amano McGann

**Comment by catodd** [comment]
Hi Chi, can you share that with my work email?

**Comment by corytodd** [comment]
Thanks for sharing this video. The jam is due to the printer being in presenter mode without adequate clearance beneath the printer. We recommend using continuous mode when testing on your workbench.

For the issue of the image getting broken up like that, we're looking into that now.

**Comment by corytodd** [comment]
Please use the new Logos API in v0.3.1 of this library. That will resolve the issue.
