### ISSUE TITLE
Missing DLL?

### ISSUE THREAD

**Issue by IcarianOM** [PyramidTechnologies/PTI.Reliance.Tools#9]
Exception thrown: 'System.DllNotFoundException' in PTIRelianceLib.dll
Exception thrown: 'PTIRelianceLib.PTIException' in PTIRelianceLib.dll
CheckTermalPrinterStatus Exception: Missing hidapi library. This dll requires access to a copy of hidapi for your system.
If you installed this package from Nuget, this is a bug on our end. File an bug report on Github:  https://github.com/PyramidTechnologies/PTI.Reliance.Tools/issues

**Comment by corytodd** [comment]
- Did you install through nuget
- What version of this library are you using
- What framework are you targetting
- What OS and bitness are you deployed on

**Comment by IcarianOM** [comment]
- Did you install through nuget
**YES**
- What version of this library are you using
1.2.1
- What framework are you targetting
4.7.1
- What OS and bitness are you deployed on
Windows 7 Compact edition via Remote Tools, Visual Studio 2019

Fixed by adding build path to System PATH Environment on the new remote site. Only that DLL was missing (im using other packages as well without exception of missing dll), thats why i think there is a hardlink to the development where the nuget package was installed)

**Comment by corytodd** [comment]
I see, so remote deployment is not picking up the dependency. Your solution works. 

Alternatively you could include the hidapi.dll in your deployment process. hidapi.dll should be at the same directory as PTIRelianceLib.dll. For Windows installations there is also a dependency on vc_runtime 2015.
